version: '3.8'

services:
  yolo-api:
    build: .
    container_name: yolo-api
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/letsencrypt
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - yolo-api
    networks:
      - api-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-challenge:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email seu-email@exemplo.com --agree-tos --no-eff-email -d api.seudominio.com

networks:
  api-network:
    driver: bridge

volumes:
  ssl-data:
  logs-data:
